version: '3.9'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-nextjs
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./:/app
    ports:
      - "3001:3001" # nextapp
      - "5555:5555" # prisma studio
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/ecommercedb

  mysql:
    image: mysql:latest
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommercedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

# persistent volumes
volumes:
  mysql_data:
